### ISSUE TITLE
multi-threshold alerts import errors out

### ISSUE THREAD

**Issue by muhammadnkhan** [snltd/wavefront-cli#122]
multi-threshold alert import errors out with "Required field condition cannot be empty in entity". 

$ wf alert import multi_alert.json -D
[nil,
 "{\"name\":\"script_testing\",\"condition\":\"\",\"minutes\":5,\"target\":null,\"severity\":null,\"displayExpression\":\"ts(sample.WF.run.time)\",\"tags\":{\"customerTags\":[]},\"additionalInformation\":\"\",\"resolveAfterMinutes\":null}"]
#<Faraday::Response:0x00007fac060c5648
 @env=
  #<struct Faraday::Env
   method=:post,
   body=
    "{\"status\":{\"result\":\"ERROR\",\"message\":\"Required field condition cannot be empty in entity JSON\",\"code\":400}}",
   url=#<URI::HTTPS https://cluster.wavefront.com/api/v2/alert>,
   request=
    #<struct Faraday::RequestOptions
     params_encoder=nil,
     proxy=nil,
     bind=nil,
     timeout=nil,
     open_timeout=nil,
     write_timeout=nil,
     boundary=nil,
     oauth=nil,
     context=nil>,
   request_headers=
    {"User-agent"=>"wavefront-cli-4.6.1",
     "Authorization"=>"Bearer token",
     "Content-type"=>"application/json",
     "Accept"=>"application/json"},
   ssl=
    #<struct Faraday::SSLOptions
     verify=true,
     ca_file=nil,
     ca_path=nil,
     verify_mode=nil,
     cert_store=nil,
     client_cert=nil,
     client_key=nil,
     certificate=nil,
     private_key=nil,
     verify_depth=nil,
     version=nil,
     min_version=nil,
     max_version=nil>,
   parallel_manager=nil,
   params=nil,
   response=#<Faraday::Response:0x00007fac060c5648 ...>,
   response_headers=
    {"server"=>"nginx",
     "date"=>"Thu, 13 Feb 2020 21:59:36 GMT",
     "content-type"=>"application/json",
     "content-length"=>"108",
     "connection"=>"close"},
   status=400,
   reason_phrase="Bad Request">,
 @on_complete_callbacks=[]>
SDK DEBUG: #<Wavefront::Response:0x00007fac06128608 @opts={:debug=>true, :noop=>false, :verbose=>false}, @logger=#<Wavefront::Logger:0x00007fac061285e0 @logger=nil, @verbose=nil, @debug=true>, @status=#<Wavefront::Type::Status:0x00007fac06128338 @obj={:result=>"ERROR", :message=>"Required field condition cannot be empty in entity JSON", :code=>400}, @status=400>, @response={"status"=>
  {"result"=>"ERROR",
   "message"=>"Required field condition cannot be empty in entity JSON",
   "code"=>400}}
>

Multi-threshold alerts can have multiple targets like below and can have multiple targets for each severity.

"targets":{"warn":"target:fvWSnjFDMiL2eB6O","severe":"target:vQdcoWMaLy0HTQ7X"}

**Comment by snltd** [comment]
This is fixed by PR #123 , and in release 5.0.1.

Thank you for the report.
