### ISSUE TITLE
Does not support traces and spans for distributed tracing

### ISSUE THREAD

**Issue by dambott** [snltd/wavefront-cli#137]
The Wavefront API supports requests for traces e.g. https://demo.wavefront.com/api/v2/chart/api?e=1601591832&g=s&i=false&q=limit(1,traces(application=%22beachshirts%22))&s=1600581700&sorted=false

Running a similar query in wf does not seem to work:

wfcli % wf query "limit(1,traces(application="beachshirts"))" -s 1600581700 -e 1601591832
name         limit(1,traces(application=beachshirts))
query        limit(1,traces(application=beachshirts))
timeseries   <none>
events       <none>

It would be a useful addition to the tool

**Comment by snltd** [comment]
Added to release 8.1.0. I don't use traces myself, but I hope the way I've chosen to present the data is useful. If it's not, please let me know and we'll work out something better. Thanks for the report.

**Comment by dambott** [comment]
Fantastic ! JSON is perfect, plain text is a nice bonus. Thanks for the super fast turnaround !
