### ISSUE TITLE
It would be great to have a dashboard export function 

### ISSUE THREAD

**Issue by dambott** [snltd/wavefront-cli#141]
As a Wavefront SE, I often want to push dashboards to prospect eval accounts, and within VMware teams want to share dashboards across accounts too. There is a REST API to Get and Put a single dashboard, but the CLI does not seem to support exporting a single, named dashboard. It would be really cool to be able to pull one, save it to a file, and then import  it to a different account. Right now I think the only way to do it is 'dump' them all, then edit the json...   Today, without this functionality, I cut and paste the JSON in the UI. It works for sure, but is not automatable..

**Comment by snltd** [comment]
You can export a single dashboard with `wf dashboard describe -f json <id> > file.json`, and import it with `wf dashboard import <file>`. (`-f yaml` also works, should you prefer it for any reason.)

**Comment by dambott** [comment]
Ah, excellent thanks - did not realize that. Not obvious, but excellent that it works. Thanks for all your work on this - it's a huge asset !
