### ISSUE TITLE
Create event with tags in one fell swoop

### ISSUE THREAD

**Issue by stephenchu** [snltd/wavefront-cli#22]
Looking at the [API doc of #createEvent](https://metrics.wavefront.com/api-docs/ui/#!/Event/createEvent), it seems it is possible to create an event and optionally tagging it during the POST.  The help doc for `wf event create` seems to say that one cannot:

```
Usage:
  wf event create [-DnV] [-c file] [-P profile] [-E endpoint] [-t token] [-d description] [-s time] [-i | -e time] [-S severity] [-T type] [-H host...] [-N] <event>
  wf event wrap [-DnV] [-c file] [-P profile] [-E endpoint] [-t token] [-C command] [-d description] [-S severity] [-T type] [-H host...] <event>
```

Is it supported, and if not, can this be a feature request? It's very handy especially when combined with `--command` option, rather than having to tag events as an after-action.

Version: 2.1.4

**Comment by snltd** [comment]
Good idea. I'll add it ASAP.

**Comment by snltd** [comment]
This is added in 2.1.5. Please let me know if there are any problems.
